name: CI Pipeline

on:
  push:
    branches:
      - tdd_zadanie
  pull_request:

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Format Python Code with Black and isort
      run: |
        black .
        isort .

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        coverage report

    - name: Run Super-Linter
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
